#include <stdio.h>

// this is an optimized strcpy as can been seen generated by VC++

void __strncpy(char *dst, char *src, int len)
{
  int i; // esi@1
  char *dst_0; // ecx@2

  i = len;
  if ( len )
  {
    dst_0 = dst;
    do
    {
      *dst_0 = dst_0[src - dst];
      ++dst_0;
      --i;
    }
    while ( i );
  }

}

void main() {

  char a[] = "abcd";
  char b[] = "efgh";

  printf("before:\n");
  printf("a: %s\n", a);
  printf("b: %s\n", b);

  __strncpy(a, b, 3);

  printf("after:\n");
  printf("a: %s\n", a);
  printf("b: %s\n", b);

}
